x=int(input("Please enter 1st number = "))
y=int(input("Please enter 2st number = "))
z=int(input("Please enter 3st number = "))
print("The max of three values is ")
print(max(x,y,z))
input("Please Press Enter to Exit ")
